-- CRIA O BANDO DE DADOS
CREATE DATABASE bdi221
GO
-- SELECIONA O BANDO DE DADOS A SER UTILIZADO
USE bdi221
GO

-- CRIACAO TABELA PRODUTOS
DROP TABLE DBO.PRODUTO;
GO

CREATE TABLE PRODUTO(
    ID INT IDENTITY(1,1) NOT NULL,
    NOME VARCHAR(50),
    DESCRICAO VARCHAR(225),
    TIPO CHAR(1),
    VALOR DECIMAL(5,2),
    CONSTRAINT PK_PRODUTO PRIMARY KEY(ID)
);
GO

-- CRIAÇÃO TABELA PRONTUARIO
DROP TABLE DBO.PRONTUARIO;
GO

CREATE TABLE PRONTUARIO(
    ID INT IDENTITY(1,1) NOT NULL,
    DESCRICAO VARCHAR(255),
    TEMPERATURA DECIMAL(5,2),
    PESO DECIMAL(6,2)
    CONSTRAINT PK_PRONTUARIO PRIMARY KEY(ID)
);
GO

-- CRIAÇÃO TABELA EPT
DROP TABLE DBO.PET;
GO

CREATE TABLE PET(
    ID INT IDENTITY(1,1) NOT NULL,
    ID_PRONTUARIO INT,
    NOME VARCHAR(50),
    ESPECIE VARCHAR(50),
    PORTE VARCHAR(50),
    DT_NASC DATE,
    CONSTRAINT PK_PET PRIMARY KEY(ID),
    CONSTRAINT FK_PRONTUARIO FOREIGN KEY(ID_PRONTUARIO)
    REFERENCES PRONTUARIO(ID)
);
GO

-- CRIAÇÃO TABELA FORMA_PAGAMENTO
DROP TABLE DBO.FORMA_PAGAMENTO;
GO

CREATE TABLE FORMA_PAGAMENTO(
    ID INT IDENTITY(1,1) NOT NULL,
    DESCRICAO VARCHAR(50) NOT NULL,
    CONSTRAINT PK_FORMA_PAGAMENTO PRIMARY KEY(ID)
);
GO

-- CRIAÇÃO TABELA ENDEREÇO
DROP TABLE DBO.ENDERECO;
GO

CREATE TABLE ENDERECO(
    ID INT IDENTITY(1,1) NOT NULL,
    RUA VARCHAR(255) NOT NULL,
    NUMER0 INT NULL,
    CEP INT NOT NULL,
    BAIRRO VARCHAR(100) NOT NULL,
    CIDADE VARCHAR(100) NOT NULL,
    ESTADO VARCHAR(100) NOT NULL,
    PAIS VARCHAR(100) NOT NULL,
    COMPLEMENTO VARCHAR(255) NULL
    CONSTRAINT PK_ENDERECO PRIMARY KEY(ID)
);
GO

-- CRIAÇÃO TABELA FUNCIONARIO
DROP TABLE DBO.FUNCIONARIO;
GO

CREATE TABLE FUNCIONARIO(
    ID INT IDENTITY(1,1) NOT NULL,
    ID_ENDERECO INT NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    CPF VARCHAR(11) NOT NULL,
    TIPO CHAR(1) NULL,
    SALARIO DECIMAL(6,2) NOT NULL,
    NUM_CONSELHO INT NULL,
    ESPECIALIDADE VARCHAR(20) NULL,
    COMISSAO DECIMAL(4,2),
    CONSTRAINT PK_FUNCIONARIO PRIMARY KEY(ID),
    CONSTRAINT FK_FUNCIONARIO_ENDERECO FOREIGN KEY(ID)
    REFERENCES DBO.FUNCIONARIO(ID)
);
GO

-- CRIAÇÃO TABELA CLIENTE
DROP TABLE DBO.CLIENTE;
GO

CREATE TABLE CLIENTE(
    ID INT IDENTITY(1,1) NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    ID_ENDERECO INT NOT NULL,
    CONSTRAINT PK_CLIENTE PRIMARY KEY(ID),
    CONSTRAINT FK_CLIENTE_ENDERECO FOREIGN KEY (ID_ENDERECO)
    REFERENCES DBO.ENDERECO(ID)
);
GO

-- CRIAÇÃO TABELA CLIENTE_PET
DROP TABLE DBO.CLIENTE_PET;
GO

CREATE TABLE CLIENTE_PET(
    ID INT IDENTITY(1,1) NOT NULL,
    ID_CLIENTE INT NOT NULL,
    ID_PET INT NOT NULL,
    CONSTRAINT PK_CLIENTE_PET PRIMARY KEY(ID),
    CONSTRAINT FK_CLIENTE_PET_CLIENTE FOREIGN KEY (ID_CLIENTE)
    REFERENCES DBO.CLIENTE(ID),
    CONSTRAINT FK_CLIENTE_PET_PET FOREIGN KEY (ID_PET)
    REFERENCES DBO.PET(ID)
)
GO

-- CRIAÇÃO TABELA EMAIL
DROP TABLE DBO.EMAIL;
GO

CREATE TABLE EMAIL(
    ID INT IDENTITY(1,1) NOT NULL,
    ID_CLIENTE INT NULL,
    ID_FUNCIONARIO INT NULL,
    EMAIL VARCHAR(100),
    CONSTRAINT PK_EMAIL PRIMARY KEY(ID),
    CONSTRAINT FK_EMAIL_CLIENTE FOREIGN KEY (ID_CLIENTE)
    REFERENCES DBO.CLIENTE(ID),
    CONSTRAINT FK_EMAIL_FUNCIONARIO FOREIGN KEY (ID_FUNCIONARIO)
    REFERENCES DBO.FUNCIONARIO(ID)
);
GO


-- CRIAÇÃO TABELA TELEFONE
DROP TABLE DBO.TELEFONE;
GO

CREATE TABLE TELEFONE(
    ID INT IDENTITY(1,1) NOT NULL,
    ID_CLIENTE INT NULL,
    ID_FUNCIONARIO INT NULL,
    TELEFONE VARCHAR(15),
    CONSTRAINT PK_TELEFONE PRIMARY KEY(ID),
    CONSTRAINT FK_TELEFONE_CLIENTE FOREIGN KEY (ID_CLIENTE)
    REFERENCES DBO.CLIENTE(ID),
    CONSTRAINT FK_TELEFONE_FUNCIONARIO FOREIGN KEY (ID_FUNCIONARIO)
    REFERENCES DBO.FUNCIONARIO(ID)
);
GO

-- CRIAÇÃO TABELA VENDA
DROP TABLE DBO.VENDA;
GO

CREATE TABLE VENDA(
    ID INT IDENTITY(1,1) NOT NULL,
    CONSTRAINT PK_VENDA PRIMARY KEY(ID)
);
GO

-- CRIAÇÃO TABELA VENDA_PRODUTO
DROP TABLE DBO.VENDA_PRODUTO;
GO

CREATE TABLE VENDA_PRODUTO(
    ID INT IDENTITY(1,1) NOT NULL,
    ID_VENDA INT NOT NULL,
    ID_PRODUTO INT NOT NULL,
    CONSTRAINT PK_VENDA_PRODUTO PRIMARY KEY(ID),
    CONSTRAINT FK_VENDA_PRODUTO_VENDA FOREIGN KEY (ID_VENDA)
    REFERENCES DBO.VENDA(ID),
    CONSTRAINT FK_VENDA_PRODUTO_PRODUTO FOREIGN KEY (ID_PRODUTO)
    REFERENCES DBO.PRODUTO(ID)
);
GO

-- CRIAÇÃO TABELA VENDA_FORMA_PAGAMENTO
DROP TABLE DBO.VENDA_FORMA_PAGAMENTO;
GO

CREATE TABLE VENDA_FORMA_PAGAMENTO(
    ID INT IDENTITY(1,1) NOT NULL,
    ID_VENDA INT NOT NULL,
    ID_FORMA_PAGAMENTO INT NOT NULL,
    CONSTRAINT PK_VENDA_FORMA_PAGAMENTO PRIMARY KEY(ID),
    CONSTRAINT FK_VENDA_FORMA_PAGAMENTO_VENDA FOREIGN KEY (ID_VENDA)
    REFERENCES DBO.VENDA(ID),
    CONSTRAINT FK_VENDA_FORMA_PAGAMENTO_FORMA_PAGAMENTO FOREIGN KEY (ID_FORMA_PAGAMENTO)
    REFERENCES DBO.FORMA_PAGAMENTO(ID)
);
GO

-- CRIAÇÃO TABELA VENDA_FUNCIONARIO
DROP TABLE DBO.VENDA_FUNCIONARIO;
GO

CREATE TABLE VENDA_FUNCIONARIO(
    ID INT IDENTITY(1,1) NOT NULL,
    ID_VENDA INT NOT NULL,
    ID_FUNCIONARIO INT NOT NULL,
    CONSTRAINT PK_VENDA_FUNCIONARIO PRIMARY KEY(ID),
    CONSTRAINT FK_VENDA_FUNCIONARIO_VENDA FOREIGN KEY (ID_VENDA)
    REFERENCES DBO.VENDA(ID),
    CONSTRAINT FK_VENDA_FUNCIONARIO_FUNCIONARIO FOREIGN KEY (ID_FUNCIONARIO)
    REFERENCES DBO.FUNCIONARIO(ID)
);
GO

-- CRIAÇÃO TABELA VENDA_CLIENTE
DROP TABLE DBO.VENDA_CLIENTE;
GO

CREATE TABLE VENDA_CLIENTE(
    ID INT IDENTITY(1,1) NOT NULL,
    ID_VENDA INT NOT NULL,
    ID_CLIENTE INT NOT NULL,
    CONSTRAINT PK_VENDA_CLIENTE PRIMARY KEY(ID),
    CONSTRAINT FK_VENDA_CLIENTE_VENDA FOREIGN KEY (ID_VENDA)
    REFERENCES DBO.VENDA(ID),
    CONSTRAINT FK_VENDA_CLIENTE_CLIENTE FOREIGN KEY (ID_CLIENTE)
    REFERENCES DBO.CLIENTE(ID)
);
GO